<?php

use App\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arrPermissions = [
            "Manage User",
            "Create User",
            "Edit User",
            "Delete User",
            "Show User",
            "Manage Account",
            "Edit Account",
            "Delete Account",
            "Show Account",
            "Create Account",
            "Create Contact",
            "Show Contact",
            "Edit Contact",
            "Manage Contact",
            "Delete Contact",
            "Create Lead",
            "Edit Lead",
            "Show Lead",
            "Manage Lead",
            "Delete Lead",
            "Create Opportunities",
            "Delete Opportunities",
            "Manage Opportunities",
            "Edit Opportunities",
            "Show Opportunities",
            "Show CommonCase",
            "Edit CommonCase",
            "Create CommonCase",
            "Delete CommonCase",
            "Manage CommonCase",
            "Create Meeting",
            "Delete Meeting",
            "Edit Meeting",
            "Manage Meeting",
            "Show Meeting",
            "Show Call",
            "Edit Call",
            "Create Call",
            "Delete Call",
            "Manage Call",
            "Show Task",
            "Edit Task",
            "Create Task",
            "Manage Task",
            "Delete Task",
            "Show Document",
            "Edit Document",
            "Create Document",
            "Manage Document",
            "Delete Document",
            "Show Campaign",
            "Edit Campaign",
            "Delete Campaign",
            "Create Campaign",
            "Manage Campaign",
            "Show Quote",
            "Edit Quote",
            "Create Quote",
            "Manage Quote",
            "Delete Quote",
            "Create SalesOrder",
            "Show SalesOrder",
            "Edit SalesOrder",
            "Delete SalesOrder",
            "Manage SalesOrder",
            "Create Invoice",
            "Show Invoice",
            "Edit Invoice",
            "Delete Invoice",
            "Manage Invoice",
            "Create Product",
            "Delete Product",
            "Manage Product",
            "Show Product",
            "Edit Product",
            "Create Report",
            "Delete Report",
            "Manage Report",
            "Show Report",
            "Edit Report",
            "Edit Role",
            "Delete Role",
            "Manage Role",
            "Create Role",
            "Edit AccountType",
            "Delete AccountType",
            "Manage AccountType",
            "Create AccountType",
            "Edit AccountIndustry",
            "Delete AccountIndustry",
            "Manage AccountIndustry",
            "Create AccountIndustry",
            "Edit LeadSource",
            "Delete LeadSource",
            "Manage LeadSource",
            "Create LeadSource",
            "Edit OpportunitiesStage",
            "Delete OpportunitiesStage",
            "Manage OpportunitiesStage",
            "Create OpportunitiesStage",
            "Edit CaseType",
            "Delete CaseType",
            "Manage CaseType",
            "Create CaseType",
            "Edit DocumentType",
            "Delete DocumentType",
            "Manage DocumentType",
            "Create DocumentType",
            "Edit DocumentFolder",
            "Delete DocumentFolder",
            "Manage DocumentFolder",
            "Create DocumentFolder",
            "Edit CampaignType",
            "Delete CampaignType",
            "Manage CampaignType",
            "Create CampaignType",
            "Edit TargetList",
            "Delete TargetList",
            "Manage TargetList",
            "Create TargetList",
            "Edit ProductCategory",
            "Delete ProductCategory",
            "Manage ProductCategory",
            "Create ProductCategory",
            "Edit ProductBrand",
            "Delete ProductBrand",
            "Manage ProductBrand",
            "Create ProductBrand",
            "Edit ProductTax",
            "Delete ProductTax",
            "Manage ProductTax",
            "Create ProductTax",
            "Edit ShippingProvider",
            "Delete ShippingProvider",
            "Manage ShippingProvider",
            "Create ShippingProvider",
            "Edit TaskStage",
            "Delete TaskStage",
            "Manage TaskStage",
            "Create TaskStage",
            'Manage Plan',
            'Create Plan',
            'Edit Plan',
            'Manage Order',
            'Delete Coupon',
            'Manage Coupon',
            'Create Coupon',
            'Edit Coupon',
            'Manage Form Builder',
            'Create Form Builder',
            'Edit Form Builder',
            'Delete Form Builder',
            'Show Form Builder',
            'Manage Form Field',
            'Create Form Field',
            'Edit Form Field',
            'Delete Form Field',
        ];

        foreach($arrPermissions as $ap)
        {
            Permission::create(['name' => $ap]);
        }


        // Super admin
        $superAdminRole        = Role::create(
            [
                'name' => 'super admin',
                'created_by' => 0,
            ]
        );
        $superAdminPermissions = [
            'Show User',
            'Manage User',
            'Create User',
            'Edit User',
            'Delete User',
            'Manage Plan',
            'Create Plan',
            'Edit Plan',
            'Manage Order',
            'Delete Coupon',
            'Manage Coupon',
            'Create Coupon',
            'Edit Coupon',

        ];

        foreach($superAdminPermissions as $ap)
        {
            $permission = Permission::findByName($ap);
            $superAdminRole->givePermissionTo($permission);
        }

        $superAdmin = User::create(
            [
                'username' => 'Super Admin',
                'name' => 'Super Admin',
                'email' => 'superadmin@example.com',
                'password' => Hash::make('1234'),
                'type' => 'super admin',
                'lang' => 'en',
                'avatar' => 'avatar.png',
                'created_by' => 0,
            ]
        );
        $superAdmin->assignRole($superAdminRole);

        // owner

        $ownerRole        = Role::create(
            [
                'name' => 'Owner',
                'created_by' => $superAdmin->id,
            ]
        );
        $ownerPermissions = [
            "Manage User",
            "Create User",
            "Edit User",
            "Delete User",
            "Show User",
            "Manage Account",
            "Edit Account",
            "Delete Account",
            "Show Account",
            "Create Account",
            "Create Contact",
            "Show Contact",
            "Edit Contact",
            "Manage Contact",
            "Delete Contact",
            "Create Lead",
            "Edit Lead",
            "Show Lead",
            "Manage Lead",
            "Delete Lead",
            "Create Opportunities",
            "Delete Opportunities",
            "Manage Opportunities",
            "Edit Opportunities",
            "Show Opportunities",
            "Show CommonCase",
            "Edit CommonCase",
            "Create CommonCase",
            "Delete CommonCase",
            "Manage CommonCase",
            "Create Meeting",
            "Delete Meeting",
            "Edit Meeting",
            "Manage Meeting",
            "Show Meeting",
            "Show Call",
            "Edit Call",
            "Create Call",
            "Delete Call",
            "Manage Call",
            "Show Task",
            "Edit Task",
            "Create Task",
            "Manage Task",
            "Delete Task",
            "Show Document",
            "Edit Document",
            "Create Document",
            "Manage Document",
            "Delete Document",
            "Show Campaign",
            "Edit Campaign",
            "Delete Campaign",
            "Create Campaign",
            "Manage Campaign",
            "Show Quote",
            "Edit Quote",
            "Create Quote",
            "Manage Quote",
            "Delete Quote",
            "Create SalesOrder",
            "Show SalesOrder",
            "Edit SalesOrder",
            "Delete SalesOrder",
            "Manage SalesOrder",
            "Create Invoice",
            "Show Invoice",
            "Edit Invoice",
            "Delete Invoice",
            "Manage Invoice",
            "Create Product",
            "Delete Product",
            "Manage Product",
            "Show Product",
            "Edit Product",
            "Create Report",
            "Delete Report",
            "Manage Report",
            "Show Report",
            "Edit Report",
            "Edit Role",
            "Delete Role",
            "Manage Role",
            "Create Role",
            "Edit AccountType",
            "Delete AccountType",
            "Manage AccountType",
            "Create AccountType",
            "Edit AccountIndustry",
            "Delete AccountIndustry",
            "Manage AccountIndustry",
            "Create AccountIndustry",
            "Edit LeadSource",
            "Delete LeadSource",
            "Manage LeadSource",
            "Create LeadSource",
            "Edit OpportunitiesStage",
            "Delete OpportunitiesStage",
            "Manage OpportunitiesStage",
            "Create OpportunitiesStage",
            "Edit CaseType",
            "Delete CaseType",
            "Manage CaseType",
            "Create CaseType",
            "Edit DocumentType",
            "Delete DocumentType",
            "Manage DocumentType",
            "Create DocumentType",
            "Edit DocumentFolder",
            "Delete DocumentFolder",
            "Manage DocumentFolder",
            "Create DocumentFolder",
            "Edit CampaignType",
            "Delete CampaignType",
            "Manage CampaignType",
            "Create CampaignType",
            "Edit TargetList",
            "Delete TargetList",
            "Manage TargetList",
            "Create TargetList",
            "Edit ProductCategory",
            "Delete ProductCategory",
            "Manage ProductCategory",
            "Create ProductCategory",
            "Edit ProductBrand",
            "Delete ProductBrand",
            "Manage ProductBrand",
            "Create ProductBrand",
            "Edit ProductTax",
            "Delete ProductTax",
            "Manage ProductTax",
            "Create ProductTax",
            "Edit ShippingProvider",
            "Delete ShippingProvider",
            "Manage ShippingProvider",
            "Create ShippingProvider",
            "Edit TaskStage",
            "Delete TaskStage",
            "Manage TaskStage",
            "Create TaskStage",
            'Manage Plan',
            'Manage Order',
            'Manage Form Builder',
            'Create Form Builder',
            'Edit Form Builder',
            'Delete Form Builder',
            'Show Form Builder',
            'Manage Form Field',
            'Create Form Field',
            'Edit Form Field',
            'Delete Form Field',

        ];
        foreach($ownerPermissions as $ap)
        {
            $permission = Permission::findByName($ap);
            $ownerRole->givePermissionTo($permission);
        }
        $owner = User::create(
            [
                'username' => 'owner',
                'name' => 'owner',
                'email' => 'owner@example.com',
                'password' => Hash::make('1234'),
                'type' => 'owner',
                'lang' => 'en',
                'title' => '-',
                'avatar' => 'avatar.png',
                'plan' => 1,
                'created_by' => 0,
            ]
        );
        $owner->assignRole($ownerRole);
    }
}
